version: '3.7'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - skripsi_mongo:/data/db

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    volumes:
      - skripsi_kafka:/bitnami
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  emqx:
    image: emqx:latest
    environment:
      - 'EMQX_CLUSTER__DNS__INTERVAL=5000'
    ports:
      - '1883:1883'
      - '8083:8083'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - skripsi_redis:/data

volumes:
  skripsi_mongo:
    driver: local
  skripsi_kafka:
    driver: local
  skripsi_redis:
    driver: local
